/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fuzhu8_inspector_jni_TraceAnti */

#ifndef _Included_com_fuzhu8_inspector_jni_TraceAnti
#define _Included_com_fuzhu8_inspector_jni_TraceAnti
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fuzhu8_inspector_jni_TraceAnti
 * Method:    _traceAnti
 * Signature: (Ljava/lang/String;ZZZZ)V
 */
JNIEXPORT void JNICALL Java_com_fuzhu8_inspector_jni_TraceAnti__1traceAnti
  (JNIEnv *, jobject, jstring, jboolean, jboolean, jboolean, jboolean, jint);

/*
 * Class:     com_fuzhu8_inspector_jni_TraceAnti
 * Method:    _testAntiHook
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_fuzhu8_inspector_jni_TraceAnti__1testAntiHook
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_fuzhu8_inspector_jni_TraceAnti
 * Method:    _nativeHook
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fuzhu8_inspector_jni_TraceAnti__1nativeHook
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fuzhu8_inspector_jni_TraceAnti
 * Method:    _enableCollectBytecode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fuzhu8_inspector_jni_TraceAnti__1enableCollectBytecode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
