/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unicorn_Unicorn_Tuple */

#ifndef _Included_unicorn_Unicorn_Tuple
#define _Included_unicorn_Unicorn_Tuple
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
