/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fuzhu8_inspector_jni_InspectorNative */

#ifndef _Included_com_fuzhu8_inspector_jni_InspectorNative
#define _Included_com_fuzhu8_inspector_jni_InspectorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fuzhu8_inspector_jni_InspectorNative
 * Method:    _initializeNative
 * Signature: (Lcom/fuzhu8/inspector/Inspector;)V
 */
JNIEXPORT void JNICALL Java_com_fuzhu8_inspector_jni_InspectorNative__1initializeNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
