/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nagapt_udog_UDogUnpacker */

#ifndef _Included_com_nagapt_udog_UDogUnpacker
#define _Included_com_nagapt_udog_UDogUnpacker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nagapt_udog_UDogUnpacker
 * Method:    doDumpByLinker
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nagapt_udog_UDogUnpacker_doDumpByLinker
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
