/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_freakishfox_xAnSo_xAnSoUnpacker */

#ifndef _Included_com_freakishfox_xAnSo_xAnSoUnpacker
#define _Included_com_freakishfox_xAnSo_xAnSoUnpacker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_freakishfox_xAnSo_xAnSoUnpacker
 * Method:    fix_section
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_freakishfox_xAnSo_xAnSoUnpacker_fix_1section
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
